// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gateway$0 from "../ssh-gateway/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "../ssh-gateway/updater/models.js";

export function AckTerminal(id: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.AckTerminal", id);
}

export function Call(method: string, path: string, body: string): $CancellablePromise<gateway$0.DesktopReply> {
    return $Call.ByName("main.App.Call", method, path, body);
}

export function CancelQuit(): $CancellablePromise<void> {
    return $Call.ByName("main.App.CancelQuit");
}

export function CancelWork(id: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.CancelWork", id);
}

export function CheckUpdate(): $CancellablePromise<updater$0.Info> {
    return $Call.ByName("main.App.CheckUpdate");
}

export function ChooseDataDir(): $CancellablePromise<void> {
    return $Call.ByName("main.App.ChooseDataDir");
}

export function CloseTerminal(id: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.CloseTerminal", id);
}

export function ConfirmOverwrite(id: string, confirmed: boolean): $CancellablePromise<void> {
    return $Call.ByName("main.App.ConfirmOverwrite", id, confirmed);
}

export function ConfirmQuit(): $CancellablePromise<void> {
    return $Call.ByName("main.App.ConfirmQuit");
}

/**
 * FrontendReady 在退出事件订阅完成后握手，避免启动期间丢失退出请求。
 */
export function FrontendReady(): $CancellablePromise<void> {
    return $Call.ByName("main.App.FrontendReady");
}

export function Info(): $CancellablePromise<gateway$0.DesktopInfo> {
    return $Call.ByName("main.App.Info");
}

export function MachineCall(id: string, target: string, operation: string, body: string): $CancellablePromise<gateway$0.DesktopReply> {
    return $Call.ByName("main.App.MachineCall", id, target, operation, body);
}

export function MachineCallConnection(id: string, target: string, operation: string, body: string, query: string): $CancellablePromise<gateway$0.DesktopReply> {
    return $Call.ByName("main.App.MachineCallConnection", id, target, operation, body, query);
}

/**
 * OpenExternalURL 将网页交给系统浏览器，保留桌面工作区。
 */
export function OpenExternalURL(address: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.OpenExternalURL", address);
}

/**
 * OpenMachineConnectionWindow 用所选账号打开独立工作页。
 */
export function OpenMachineConnectionWindow(target: string, selection: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.OpenMachineConnectionWindow", target, selection);
}

/**
 * OpenMachineWindow 在系统浏览器中打开独立工作页，沿用桌面登录。
 */
export function OpenMachineWindow(target: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.OpenMachineWindow", target);
}

export function OpenTerminal(id: string, target: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.OpenTerminal", id, target);
}

export function OpenTerminalConnection(id: string, target: string, selection: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.OpenTerminalConnection", id, target, selection);
}

export function Quit(): $CancellablePromise<void> {
    return $Call.ByName("main.App.Quit");
}

/**
 * SaveBackup 只保存已经加密的备份；路径由系统保存窗口选择。
 */
export function SaveBackup(encoded: string): $CancellablePromise<boolean> {
    return $Call.ByName("main.App.SaveBackup", encoded);
}

export function SaveSettings(settings: gateway$0.DesktopSettings, confirmed: boolean): $CancellablePromise<void> {
    return $Call.ByName("main.App.SaveSettings", settings, confirmed);
}

/**
 * SetLocale 更新界面语言，保留核心服务和现有会话。
 */
export function SetLocale(value: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.SetLocale", value);
}

export function TerminalInput(id: string, data: string, columns: number, rows: number): $CancellablePromise<void> {
    return $Call.ByName("main.App.TerminalInput", id, data, columns, rows);
}

export function TransferFile(id: string, target: string, mode: string, remote: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.TransferFile", id, target, mode, remote);
}

export function TransferFileConnection(id: string, target: string, mode: string, remote: string, query: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.TransferFileConnection", id, target, mode, remote, query);
}
