import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'

test('帐号管理、标签授权、普通用户机器页与撤权', async ({ page, browser }) => {
  const fixture = JSON.parse(readFileSync('.test-fixture/connection.json', 'utf8'))
  await page.goto('/')
  await page.getByLabel('管理员密码').fill(fixture.admin_password)
  await page.getByRole('button', { name: '进入中转台' }).click()
  const row = page.getByRole('row').filter({ hasText: fixture.target.name })
  await row.getByRole('button', { name: '编辑', exact: true }).click()
  await page.getByLabel('机器标签', { exact: true }).fill('开发')
  await page.getByLabel('机器标签', { exact: true }).press('Enter')
  await page.getByLabel('机器标签', { exact: true }).fill('共享')
  await page.getByLabel('机器标签', { exact: true }).press('Enter')
  await page.getByRole('button', { name: '保存连接', exact: true }).click()
  await expect(row).toContainText('开发')
  await page.locator('.content').getByLabel('筛选机器标签').selectOption('开发')
  await expect(row).toBeVisible()
  await page.getByRole('button', { name: '帐号管理' }).click()
  await page.getByRole('button', { name: '添加帐号' }).click()
  const editor = page.locator('dialog[open]').filter({ has: page.getByRole('heading', { name: '添加帐号' }) })
  const username = `user-${Date.now()}`
  await editor.getByLabel('用户名', { exact: true }).fill(username)
  await editor.getByLabel('初始密码').fill('browser-user-password')
  await editor.getByLabel('开发', { exact: true }).check()
  await editor.getByRole('button', { name: '保存帐号' }).click()
  const userRow = page.getByRole('row').filter({ hasText: username })
  await expect(userRow).toContainText('开发')
  const { items: users } = await (await page.request.get('/api/users')).json()
  const account = users.find((u: { username: string }) => u.username === username)
  const userContext = await browser.newContext()
  const userPage = await userContext.newPage()
  try {
    await userPage.goto('/')
    await userPage.getByLabel('用户名', { exact: true }).fill(username)
    await userPage.getByLabel('登录密码').fill('browser-user-password')
    await userPage.getByRole('button', { name: '进入中转台' }).click()
    const visibleRow = userPage.getByRole('row').filter({ hasText: fixture.target.name })
    await expect(visibleRow).toBeVisible()
    await expect(userPage.getByRole('button', { name: '帐号管理' })).toHaveCount(0)
    await expect(userPage.getByRole('button', { name: '连接日志' })).toHaveCount(0)
    await expect(userPage.getByRole('button', { name: '快捷指令' })).toHaveCount(0)
    await expect(visibleRow.getByRole('button', { name: '编辑', exact: true })).toHaveCount(0)
    expect((await userPage.request.get('/api/users')).status()).toBe(403)
    const opening = userPage.waitForEvent('popup')
    await visibleRow.getByRole('button', { name: '终端' }).click()
    const terminalPage = await opening
    const machine = terminalPage.getByRole('main', { name: '终端机器页面' })
    await expect(machine).toBeVisible()
    await expect(machine.getByRole('button', { name: '端口映射', exact: true })).toHaveCount(0)
    await expect(machine.locator('.terminal-tab.active i.online')).toBeVisible()
    await expect(machine.getByRole('tab', { name: /笔记/ })).toBeVisible()
    const text = machine.locator('.monaco-editor textarea').first()
    await text.focus(); await terminalPage.keyboard.press('Control+A'); await terminalPage.keyboard.type('shared database note')
    await machine.getByRole('button', { name: '保存 Ctrl+S', exact: true }).click()
    await expect(machine.getByRole('button', { name: '保存 Ctrl+S', exact: true })).toHaveCount(0)
    const note = await (await page.request.post(`/api/targets/${fixture.target.id}/notes`, { data: { op: 'read' } })).json()
    expect(note.content).toBe('shared database note'); expect(note.path).toBeUndefined()
    await page.request.put(`/api/users/${account.id}`, { data: { username, enabled: true, target_ids: [], tags: [] } })
    await expect(machine.locator('.terminal-tab.active i.online')).toHaveCount(0)
    expect((await userPage.request.post(`/api/targets/${fixture.target.id}/notes`, { data: { op: 'read' } })).status()).toBe(403)
    await userPage.reload()
    await expect(userPage.getByText('暂无获授权的机器')).toBeVisible()
    // 另一个用户登录不会清除管理员会话。
    expect((await page.request.get('/api/users')).status()).toBe(200)
  } finally {
    await userContext.close()
    await page.request.delete(`/api/users/${account.id}`, { data: {} })
    const targets = await (await page.request.get('/api/targets/options')).json()
    const target = await (await page.request.get(`/api/targets/${fixture.target.id}`)).json()
    await page.request.put(`/api/targets/${fixture.target.id}`, { data: { ...target, tags: [] } })
  }
})
