import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'

test('编辑与全局白名单快速填入当前 IP，保留已有来源和有效期', async ({page}) => {
 const fixture=JSON.parse(readFileSync('.test-fixture/connection.json','utf8'))
 await page.goto('/')
 await page.getByLabel('管理员密码').fill(fixture.admin_password)
 await page.getByRole('button',{name:'进入中转台'}).click()
 await expect(page.getByRole('heading',{name:'SSH 连接',exact:true})).toBeVisible()
 const me=await (await page.request.get('/api/me')).json()
 const row=page.getByRole('row').filter({hasText:fixture.target.name})
 await row.getByRole('button',{name:'编辑',exact:true}).click()
 const editor=page.getByRole('dialog',{name:'编辑 SSH 连接'})
 const sources=editor.getByRole('button',{name:/^访问范围/})
 if(await sources.getAttribute('aria-expanded')==='false') await sources.click()
 await expect(editor.getByRole('radio')).toHaveCount(0)
 const input=editor.getByLabel('允许的来源 IP / 网段')
 await input.fill('192.0.2.99\n198.51.100.0/24')
 await expect(editor.locator('.current-source-action')).toContainText(me.source_ip)
 await editor.getByRole('button',{name:'添加当前 IP',exact:true}).click()
 await expect(input).toHaveValue(`${me.source_ip}\n192.0.2.99\n198.51.100.0/24`)
 await expect(editor.getByRole('button',{name:'已添加',exact:true})).toBeDisabled()
 await editor.getByRole('button',{name:'取消',exact:true}).click()
 await page.getByRole('button',{name:'全局 IP 白名单',exact:true}).click()
 const dialog=page.getByRole('dialog',{name:'全局 IP 白名单',exact:true})
 const expiry=dialog.getByLabel('过期时间（本地时间）')
 const before=await expiry.inputValue()
 await expect(dialog.locator('.current-source-action')).toContainText(me.source_ip)
 await dialog.getByRole('button',{name:'填入当前 IP',exact:true}).click()
 await expect(dialog.getByLabel('来源 IP',{exact:true})).toHaveValue(me.source_ip)
 await expect(expiry).toHaveValue(before)
 await page.setViewportSize({width:390,height:844})
 await expect(dialog.getByRole('button',{name:'填入当前 IP',exact:true})).toBeInViewport()
 await page.screenshot({path:'/tmp/current-source-mobile.png'})
})
