import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'

test('登录、录入、中转设置、网页终端、来源限制、日志与删除', async ({ page }) => {
  const fixture = JSON.parse(readFileSync('.test-fixture/connection.json', 'utf8'))
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByLabel('管理员密码', { exact: true }).fill('错误密码')
  await page.getByRole('button', { name: '进入中转台' }).click()
  await expect(page.getByRole('alert')).toContainText('用户名或密码不正确')
  await page.getByLabel('管理员密码', { exact: true }).fill(fixture.admin_password)
  await page.getByRole('button', { name: '进入中转台' }).click()
  await expect(page.getByRole('heading', { name: 'SSH 连接', exact: true })).toBeVisible()

  await page.locator('.page-heading-actions').getByRole('button', { name: '＋ 添加 SSH', exact: true }).click()
  const editor = page.locator('.target-editor')
  await editor.getByLabel('名称', { exact: true }).fill('浏览器验证机器')
  await editor.getByLabel('主机 IP / 域名').fill(fixture.target.host)
  await editor.getByLabel('SSH 端口').fill(String(fixture.target.port))
  await editor.getByLabel('目标用户名', { exact: true }).fill(fixture.target.user)
  await editor.getByLabel('目标密码', { exact: true }).fill(fixture.target.target_password)
  await editor.getByRole('button', { name: '读取指纹' }).click()
  await expect(editor.getByLabel('目标主机指纹')).toHaveValue(fixture.target.host_fingerprint)
  await editor.getByRole('button', { name: /^中转凭证/ }).click()
  await editor.getByLabel('自动创建中转账号和密码').uncheck()
  await editor.getByLabel('中转用户名').fill('browser-relay')
  if (await editor.getByRole('button', { name: /^访问范围/ }).getAttribute('aria-expanded') === 'false') await editor.getByRole('button', { name: /^访问范围/ }).click()
  await editor.getByLabel('允许的来源 IP / 网段').fill('127.0.0.1')
  await editor.getByRole('button', { name: '保存连接' }).click()
  const connection = page.getByRole('dialog').filter({ has: page.getByRole('heading', { name: '中转连接参数' }) })
  await expect(connection).toBeVisible()
  await expect(connection.getByLabel('中转密码', { exact: true })).toHaveValue(/.{32}/)
  await expect(connection.getByLabel('SSH 命令')).toHaveValue(/browser-relay@127.0.0.1/)
  await connection.getByRole('button', { name: '关闭', exact: true }).click()

  const row = page.getByRole('row').filter({ hasText: '浏览器验证机器' })
  await expect(row.locator('.source-preview')).toContainText('127.0.0.1')
  const openTerminal = async () => {
    const opening = page.waitForEvent('popup')
    await row.getByRole('button', { name: '终端' }).click()
    const popup = await opening
    popup.on('pageerror', error => errors.push(error.message))
    return popup
  }
  let terminalPage = await openTerminal()
  const terminal = terminalPage.getByRole('region', { name: '网页终端' })
  await expect(terminalPage.locator('.terminal-tab.active i.online')).toBeVisible()
  await terminal.locator('.xterm-helper-textarea').pressSequentially('browser-terminal')
  await terminal.locator('.xterm-helper-textarea').press('Enter')
  await expect.poll(async () => terminal.locator('.xterm-screen').innerText()).toContain('browser-terminal')
  await terminalPage.getByRole('button', { name: '关闭终端 1', exact: true }).click()
  await expect(terminal).toHaveCount(0)
  await terminalPage.close()

  await row.getByRole('button', { name: '编辑', exact: true }).click()
  await editor.getByLabel('目标密码', { exact: true }).fill('')
  if (await editor.getByRole('button', { name: /^访问范围/ }).getAttribute('aria-expanded') === 'false') await editor.getByRole('button', { name: /^访问范围/ }).click()
  await editor.getByLabel('允许的来源 IP / 网段').fill('192.0.2.1')
  await editor.getByRole('button', { name: '保存连接' }).click()
  await expect(editor).not.toBeVisible()
  terminalPage = await openTerminal()
  await expect(terminalPage.locator('dialog[open]').filter({ hasText: '连接失败' })).toBeVisible()
  await expect(terminalPage.locator('.terminal-tab.active i.online')).toHaveCount(0)
  await terminalPage.close()

  await row.getByRole('button', { name: '编辑', exact: true }).click()
  await editor.getByRole('switch', { name: '机器是否有效' }).uncheck()
  await editor.getByRole('button', { name: '保存连接' }).click()
  await expect(row).toContainText('已禁用')
  terminalPage = await openTerminal()
  await expect(terminalPage.getByRole('tab', { name: /笔记/ })).toBeVisible()
  await expect(terminalPage.getByText('机器已禁用，仍可编辑笔记')).toBeVisible()
  await terminalPage.close()
  await page.screenshot({ path: 'test-results/dashboard.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await row.getByRole('button', { name: '编辑', exact: true }).click()
    await editor.locator('.target-editor-header').getByRole('button', { name: '删除', exact: true }).click()
  await page.getByRole('button', { name: '确认删除' }).click()
  await expect(row).toHaveCount(0)
  await expect(page.getByRole('button', { name: '连接日志' })).toHaveCount(0)
  const logs = await (await page.request.get('/api/events?page_size=100')).json()
  expect(JSON.stringify(logs.items)).toContain('WebSSH 已连接')
  expect(JSON.stringify(logs.items)).toContain('目标已删除')
  await page.getByRole('button', { name: '退出', exact: true }).click()
  await expect(page.getByLabel('管理员密码', { exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('SSH 连接内的全局 IP 白名单添加、续期与删除', async ({ page }) => {
  const fixture = JSON.parse(readFileSync('.test-fixture/connection.json', 'utf8'))
  await page.goto('/')
  await page.getByLabel('管理员密码', { exact: true }).fill(fixture.admin_password)
  await page.getByRole('button', { name: '进入中转台' }).click()
  await expect(page.getByRole('heading', { name: 'SSH 连接', exact: true })).toBeVisible()
  await expect(page.locator('.sidebar').getByRole('button', { name: '全局 IP 白名单' })).toHaveCount(0)
  await expect(page.getByRole('navigation', { name: 'SSH 连接设置' })).toHaveCount(0)
  const dialog = page.getByRole('dialog', { name: '全局 IP 白名单', exact: true })
  await page.getByRole('textbox', { name: '搜索连接' }).fill('保留筛选')
  await page.getByRole('button', { name: '全局 IP 白名单', exact: true }).click()
  await expect(dialog).toBeVisible()
  await expect(dialog).toContainText('仅用于 SSH 连接的来源 IP 授权')
  await expect(dialog.getByText('正在加载白名单…')).toHaveCount(0)
  await page.screenshot({ path: 'test-results/global-ip-dialog-desktop.png' })
  await dialog.getByRole('button', { name: '关闭全局 IP 白名单' }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('textbox', { name: '搜索连接' })).toHaveValue('保留筛选')
  await page.getByRole('button', { name: '切换黑色主题', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: '全局 IP 白名单', exact: true }).click()
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('button', { name: '关闭', exact: true })).toBeInViewport()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.route('**/api/global-ips', route => route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ error: '白名单保存失败' }) }), { times: 1 })
  await dialog.getByLabel('来源 IP', { exact: true }).fill('2001:db8::123')
  await dialog.getByRole('button', { name: '添加 / 更新有效期' }).click()
  await expect(dialog.getByRole('alert')).toContainText('白名单保存失败')
  await page.getByLabel('来源 IP', { exact: true }).fill('2001:db8::123')
  await page.getByRole('button', { name: '添加 / 更新有效期' }).click()
  const row = page.getByRole('row').filter({ hasText: '2001:db8::123' })
  await expect(row).toContainText('有效')
  await expect(dialog.getByRole('status')).toContainText('全局白名单已保存')
  await page.screenshot({ path: 'test-results/global-ip-dialog-mobile.png' })
  await row.getByRole('button', { name: '续期' }).click()
  await expect(page.getByLabel('来源 IP', { exact: true })).toHaveValue('2001:db8::123')
  await page.getByRole('button', { name: '添加 / 更新有效期' }).click()
  await expect(row).toHaveCount(1)
  await page.reload()
  await page.getByRole('button', { name: '全局 IP 白名单' }).click()
  await expect(row).toContainText('有效')
  await row.getByRole('button', { name: '删除' }).click()
  await expect(row).toHaveCount(0)
  await expect(dialog.getByRole('status')).toContainText('已删除')
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('textbox', { name: '搜索连接' })).toBeVisible()
})

// Keep navigation visible for these workflows; default collapse is covered by compact-ui.spec.ts.
test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => {
    if (localStorage.getItem('ssh-gateway:sidebar-collapsed') === null)
      localStorage.setItem('ssh-gateway:sidebar-collapsed', 'false')
  })
})
