import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'
import net from 'node:net'
import http from 'node:http'
async function unusedPort(): Promise<number> { return new Promise((resolve, reject) => { const server = net.createServer(); server.on('error', reject); server.listen(0, '127.0.0.1', () => { const port = (server.address() as net.AddressInfo).port; server.close(() => resolve(port)) }) }) }
async function echo(port: number): Promise<string> { return new Promise((resolve, reject) => { const socket = net.connect(port, '127.0.0.1', () => socket.write('真实浏览器转发')); socket.setTimeout(3000, () => { socket.destroy(); reject(new Error('转发超时')) }); socket.on('error', reject); socket.on('data', data => { socket.destroy(); resolve(data.toString()) }) }) }
test('映射总览、四种真实转发、冲突、修改、单机同步及删除', async ({ page }) => {
  test.setTimeout(90_000)
  page.setDefaultTimeout(10_000)
  const fixture = JSON.parse(readFileSync('.test-fixture/connection.json', 'utf8'))
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message)); page.on('dialog', d => d.accept())
  await page.goto('/'); await page.getByLabel('管理员密码').fill(fixture.admin_password); await page.getByRole('button', { name: '进入中转台' }).click()
  await expect(page.getByRole('heading', { name: 'SSH 连接', exact: true })).toBeVisible()
  const put = await page.request.post('/api/targets', { data: fixture.mapping_target }); expect(put.ok(), await put.text()).toBeTruthy()
  await page.reload(); await page.locator('.nav-item').filter({ hasText: '端口映射' }).click()
  const overview = page.getByRole('region', { name: '端口映射总览' }), drawer = page.getByRole('dialog', { name: '端口映射配置' })
  await expect(overview.locator('.mapping-description')).toContainText('管理本地与反向转发，按需设置服务入口和访问范围。')
  await expect(overview.locator('.mapping-description').getByRole('button', { name: '查看说明', exact: true })).toBeVisible()
  const help = overview.getByRole('dialog', { name: '使用说明', exact: true })
  const helpTrigger = overview.getByRole('button', { name: '查看说明', exact: true })
  await expect(overview.getByRole('searchbox')).toHaveCount(0)
  await expect(help).not.toBeVisible()
  await helpTrigger.click()
  await expect(help).toBeVisible()
  await expect(help).toContainText('远程服务 → 中转服务器')
  await expect(help).toContainText('中转服务器服务 → 远程服务器')
  await help.getByRole('button', { name: '关闭使用说明' }).click()
  await expect(help).not.toBeVisible()
  await expect(helpTrigger).toBeFocused()
  const rows = overview.locator('tbody tr')
  let firstPort = 0
  for (const direction of ['local', 'reverse']) for (const scope of ['loopback', 'shared']) {
    const name = `${direction === 'local' ? '本地' : '反向'}${scope === 'shared' ? '共享' : '回环'}验收`, port = await unusedPort()
    if (!firstPort) firstPort = port
    await overview.getByRole('button', { name: '新增映射' }).click(); await drawer.getByLabel('所属服务器').selectOption(fixture.mapping_target.id); await drawer.getByLabel('名称', { exact: true }).fill(name)
    await drawer.locator(`input[type=radio][value=${direction}]`).check(); await drawer.getByLabel('访问范围', { exact: true }).selectOption(scope)
    await drawer.getByLabel(direction === 'local' ? '远程服务端口' : '本地服务端口', { exact: true }).fill(String(fixture.mapping_service_port)); await drawer.getByLabel(direction === 'local' ? '本地映射端口' : '远程映射端口', { exact: true }).fill(String(port))
    await drawer.getByRole('button', { name: '保存并启动' }).click(); await expect(drawer).not.toBeVisible()
    const row = rows.filter({ hasText: name }); await expect(row).toContainText('运行中'); expect(await echo(port)).toBe('真实浏览器转发')
    if (direction === 'reverse' && scope === 'loopback') {
      await expect(row.getByRole('button', { name: '打开', exact: true })).toBeDisabled()
      await expect(row.locator('.mapping-open-disabled')).toHaveAttribute('title', /仅远程服务器自身可访问/)
    } else await expect(row.getByRole('link', { name: '打开' })).toHaveAttribute('href', new RegExp(`^http://.+:${port}/$`))
  }
  await expect(rows).toHaveCount(4)
  await expect(overview.getByText('更多地址', { exact: true })).toHaveCount(0)
  await overview.getByLabel('筛选转发方向').selectOption('reverse'); await overview.getByLabel('筛选访问范围').selectOption('shared'); await expect(rows).toHaveCount(1)
  await overview.getByRole('button', { name: '清除筛选' }).click(); await page.reload(); await page.locator('.nav-item').filter({ hasText: '端口映射' }).click(); await expect(rows).toHaveCount(4)
  await page.screenshot({ path: test.info().outputPath('mapping-overview.png'), fullPage: true })
  const first = rows.filter({ hasText: '本地回环验收' }); await first.getByRole('button', { name: '停止', exact: true }).click(); await expect(first).toContainText('已停止'); await expect(first.getByRole('button', { name: '打开', exact: true })).toBeDisabled()
  await overview.getByRole('button', { name: '新增映射' }).click(); await drawer.getByLabel('所属服务器').selectOption(fixture.mapping_target.id); await drawer.getByLabel('名称', { exact: true }).fill('端口冲突'); await drawer.getByLabel('本地映射端口', { exact: true }).fill(String(firstPort)); await drawer.getByRole('button', { name: '仅保存', exact: true }).click(); await expect(drawer.getByRole('alert')).toContainText('端口已被其他规则使用'); await drawer.getByRole('button', { name: '取消', exact: true }).click()
  await first.getByRole('button', { name: '编辑', exact: true }).click(); await drawer.getByLabel('名称', { exact: true }).fill('修改后的映射'); await drawer.getByLabel('访问范围', { exact: true }).selectOption('shared'); await drawer.getByRole('button', { name: '仅保存', exact: true }).click(); await expect(drawer).toContainText('修改后的映射'); await drawer.getByRole('button', { name: '关闭端口映射', exact: true }).click(); await expect(rows.filter({ hasText: '修改后的映射' })).toContainText('允许其他机器访问')
  await page.locator('.nav-item').filter({ hasText: 'SSH 连接' }).click(); await page.getByRole('row').filter({ hasText: '转发验收服务器' }).getByRole('button', { name: /映射/ }).click(); await expect(drawer.locator('.mapping-rule')).toHaveCount(4); await expect(drawer.getByRole('link', { name: '打开' })).toHaveCount(2); await expect(drawer.getByRole('button', { name: '打开', exact: true })).toHaveCount(2)
  await drawer.getByRole('button', { name: '新增映射' }).click(); await drawer.locator('input[type=radio][value=reverse]').check(); await drawer.getByLabel('访问范围', { exact: true }).selectOption('shared'); await page.screenshot({ path: test.info().outputPath('mapping-reverse.png'), fullPage: true }); await drawer.getByRole('button', { name: '取消', exact: true }).click()
  for (let i = 0; i < 4; i++) await drawer.getByRole('button', { name: '删除', exact: true }).first().click()
  await expect(drawer.locator('.mapping-rule')).toHaveCount(0); await drawer.getByRole('button', { name: '关闭端口映射', exact: true }).click(); expect((await page.request.delete(`/api/targets/${fixture.mapping_target.id}`, { data: {} })).ok()).toBeTruthy()
  // 机器工作页使用同一套映射配置，窄屏弹窗可操作。
  const targetRow = page.getByRole('row').filter({ hasText: fixture.target.name }).first()
  const popupPromise = page.waitForEvent('popup')
  await targetRow.getByRole('button', { name: '终端' }).click()
  const machine = await popupPromise
  machine.on('pageerror', e => errors.push(e.message))
  await machine.locator('.machine-page').getByRole('button', { name: '端口映射', exact: true }).click()
  const machineDrawer = machine.getByRole('dialog', { name: '端口映射配置' })
  await expect(machineDrawer).toBeVisible()
  await machine.setViewportSize({ width: 390, height: 844 })
  await machineDrawer.getByRole('button', { name: '新增映射' }).click()
  await expect(machineDrawer.getByLabel('名称', { exact: true })).toBeVisible()
  expect(await machineDrawer.evaluate(el => el.scrollWidth <= el.clientWidth)).toBeTruthy()
  await machineDrawer.getByRole('button', { name: '取消', exact: true }).click()
  await machineDrawer.getByRole('button', { name: '关闭端口映射', exact: true }).click()
  await machine.close()
  expect(errors).toEqual([])
})


test('打开映射在新标签页访问真实网页，原工作区保持可用', async ({ page }) => {
  const fixture = JSON.parse(readFileSync('.test-fixture/connection.json', 'utf8'))
  const server = http.createServer((_req, res) => { res.setHeader('Content-Type', 'text/html; charset=utf-8'); res.end('<h1>端口映射网页验收</h1>') })
  await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve))
  const servicePort = (server.address() as net.AddressInfo).port
  const ids: string[] = []
  try {
    await page.goto('/'); await page.getByLabel('管理员密码').fill(fixture.admin_password); await page.getByRole('button', { name: '进入中转台' }).click()
    await expect(page.getByRole('heading', { name: 'SSH 连接', exact: true })).toBeVisible()
    const target = await page.request.post('/api/targets', { data: fixture.mapping_target }); expect(target.ok(), await target.text()).toBeTruthy()
    await page.reload(); await page.locator('.nav-item').filter({ hasText: '端口映射' }).click()
    const overview = page.getByRole('region', { name: '端口映射总览' })
    for (const direction of ['local', 'reverse']) {
      const port = await unusedPort(), name = `${direction} 网页验收`
      const created = await page.request.post('/api/mappings', { data: { target_id: fixture.mapping_target.id, name, direction, service_host: '127.0.0.1', service_port: servicePort, listen_port: port, scope: direction === 'local' ? 'loopback' : 'shared', auto_start: false } })
      expect(created.ok(), await created.text()).toBeTruthy()
      const { id } = await created.json(); ids.push(id)
      const started = await page.request.post(`/api/mappings/${id}/start`, { data: {} }); expect(started.ok()).toBeTruthy()
      const row = overview.locator('tbody tr').filter({ hasText: name }); await expect(row).toContainText('运行中')
      const link = row.getByRole('link', { name: '打开' }); await expect(link).toHaveAttribute('rel', 'noopener noreferrer')
      const popupPromise = page.waitForEvent('popup'); await link.click(); const popup = await popupPromise
      await expect(popup.getByRole('heading', { name: '端口映射网页验收' })).toBeVisible()
      await expect(overview).toBeVisible(); await popup.close()
    }
  } finally {
    for (const id of ids) expect((await page.request.delete(`/api/mappings/${id}`, { data: {} })).ok()).toBeTruthy()
    expect((await page.request.delete(`/api/targets/${fixture.mapping_target.id}`, { data: {} })).ok()).toBeTruthy()
    server.closeAllConnections(); await new Promise<void>(resolve => server.close(() => resolve()))
  }
})

test('映射使用居中弹窗，关闭和 Escape 直接放弃编辑', async ({ page }) => {
  const fixture = JSON.parse(readFileSync('.test-fixture/connection.json', 'utf8'))
  const prompts: string[] = []
  page.on('dialog', async dialog => { prompts.push(dialog.message()); await dialog.dismiss() })
  await page.goto('/')
  await page.getByLabel('管理员密码').fill(fixture.admin_password)
  await page.getByRole('button', { name: '进入中转台' }).click()
  await expect(page.getByRole('heading', { name: 'SSH 连接', exact: true })).toBeVisible()
  const response = await page.request.post('/api/mappings', { data: { target_id: fixture.target.id, name: '弹窗布局验收', direction: 'local', service_host: '127.0.0.1', service_port: 3000, listen_port: await unusedPort(), scope: 'loopback', auto_start: false } })
  expect(response.ok()).toBeTruthy()
  const mapping = await response.json()
  try {
    await page.locator('.nav-item').filter({ hasText: '端口映射' }).click()
    const row = page.getByRole('row').filter({ hasText: '弹窗布局验收' })
    await row.getByRole('button', { name: '编辑', exact: true }).click()
    const dialog = page.getByRole('dialog', { name: '端口映射配置' })
    await expect(dialog.getByRole('heading', { name: '编辑端口映射' })).toBeVisible()
    const box = (await dialog.boundingBox())!, viewport = page.viewportSize()!
    expect(Math.abs(box.x + box.width / 2 - viewport.width / 2)).toBeLessThan(2)
    expect(Math.abs(box.y + box.height / 2 - viewport.height / 2)).toBeLessThan(2)
    await expect(dialog.getByRole('button', { name: '保存并启动' })).toBeInViewport()
    await page.screenshot({ path: 'test-results/mapping-dialog-light.png' })
    await dialog.getByLabel('名称', { exact: true }).fill('不保存的改动')
    const help = dialog.getByRole('dialog', { name: '使用说明', exact: true })
    const helpTrigger = dialog.getByRole('button', { name: '使用说明', exact: true })
    await helpTrigger.click()
    await expect(help).toBeVisible()
    const helpBox = (await help.boundingBox())!
    expect(Math.abs(helpBox.x + helpBox.width / 2 - viewport.width / 2)).toBeLessThan(2)
    expect(Math.abs(helpBox.y + helpBox.height / 2 - viewport.height / 2)).toBeLessThan(2)
    const lightBackground = await help.evaluate(el => getComputedStyle(el).backgroundColor)
    await page.screenshot({ path: 'test-results/mapping-help-light.png' })
    await page.keyboard.press('Escape')
    await expect(help).not.toBeVisible()
    await expect(dialog).toBeVisible()
    await expect(helpTrigger).toBeFocused()
    await expect(dialog.getByLabel('名称', { exact: true })).toHaveValue('不保存的改动')
    await dialog.getByRole('button', { name: '关闭端口映射' }).click()
    await expect(dialog).not.toBeVisible()
    await row.getByRole('button', { name: '编辑', exact: true }).click()
    await expect(dialog.getByLabel('名称', { exact: true })).toHaveValue('弹窗布局验收')
    await dialog.getByLabel('名称', { exact: true }).fill('Escape 放弃改动')
    await page.keyboard.press('Escape')
    await expect(dialog).not.toBeVisible()
    await page.getByRole('button', { name: '切换黑色主题' }).click()
    await row.getByRole('button', { name: '编辑', exact: true }).click()
    await page.screenshot({ path: 'test-results/mapping-dialog-dark.png' })
    await page.setViewportSize({ width: 390, height: 844 })
    await expect(dialog.getByRole('button', { name: '关闭端口映射' })).toBeInViewport()
    expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBeTruthy()
    await dialog.getByRole('button', { name: '仅保存', exact: true }).scrollIntoViewIfNeeded()
    await expect(dialog.getByRole('button', { name: '保存并启动' })).toBeInViewport()
    await page.screenshot({ path: 'test-results/mapping-dialog-mobile.png' })
    await helpTrigger.click()
    await expect(help).toBeVisible()
    expect(await help.evaluate(el => getComputedStyle(el).backgroundColor)).not.toBe(lightBackground)
    expect(await help.evaluate(el => el.scrollWidth <= el.clientWidth)).toBeTruthy()
    await expect(help.getByRole('button', { name: '关闭使用说明' })).toBeInViewport()
    await page.screenshot({ path: 'test-results/mapping-help-dark-mobile.png' })
    await help.getByRole('button', { name: '关闭使用说明' }).click()
    await expect(help).not.toBeVisible()
    await expect(dialog).toBeVisible()
    await expect(helpTrigger).toBeFocused()
    await dialog.getByRole('button', { name: '关闭端口映射' }).click()
    expect(prompts).toEqual([])
  } finally { await page.request.delete(`/api/mappings/${mapping.id}`, { data: {} }) }
})
