import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'

test('紧凑 SSH 编辑器：自动编号、标签、多账号绑定、自动凭证和有效开关', async ({ page }) => {
  const fixture = JSON.parse(readFileSync('.test-fixture/connection.json', 'utf8'))
  const target = fixture.multi_target
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/')
  await page.getByLabel('管理员密码').fill(fixture.admin_password)
  await page.getByRole('button', { name: '进入中转台' }).click()
  await page.getByRole('button', { name: '＋ 添加 SSH', exact: true }).first().click()
  const editor = page.locator('.target-editor')
  for (const name of [/^中转凭证/, /^主机指纹/]) {
    await expect(editor.getByRole('button', { name })).toHaveAttribute('aria-expanded', 'false')
  }
  await expect(editor.getByRole('button', { name: /^访问范围/ })).toHaveAttribute('aria-expanded', 'true')
  await expect(editor.getByRole('radio', { name: '仅内网', exact: true })).toHaveCount(0)
  const privateSources = ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16', '127.0.0.0/8']
  await expect(editor.getByLabel('允许的来源 IP / 网段')).toHaveValue(privateSources.join('\n'))
  await expect(editor.getByRole('button', { name: '保存连接', exact: true })).toBeInViewport()
  await expect(editor.getByLabel('目标 ID', { exact: true })).toHaveCount(0)
  await editor.getByLabel('名称', { exact: true }).fill('多账号设计验收')
  await editor.getByLabel('主机 IP / 域名').fill(target.host)
  await editor.getByLabel('SSH 端口').fill(String(target.port))
  await editor.getByLabel('机器标签', { exact: true }).fill('测试环境')
  await editor.getByLabel('机器标签', { exact: true }).press('Enter')
  await expect(editor.getByRole('button', { name: '移除标签 测试环境' })).toBeVisible()
  await editor.getByLabel('目标用户名', { exact: true }).fill('ubuntu')
  await editor.getByLabel('目标密码', { exact: true }).fill('ubuntu-password')
  await page.screenshot({ path: 'test-results/ssh-editor-compact.png' })
  await editor.getByRole('button', { name: '添加账号' }).click()
  const root = editor.getByRole('region', { name: '目标账号 2', exact: true })
  await root.getByLabel('目标用户名', { exact: true }).fill('root')
  await root.getByRole('combobox', { name: '认证方式', exact: true }).selectOption('private_key')
  await root.getByLabel('目标私钥', { exact: true }).fill(target.logins[1].target_private_key)
  await root.getByLabel('私钥密码', { exact: true }).fill(target.logins[1].target_key_passphrase)
  await root.getByRole('radio', { name: '将 root 设为默认' }).check()
  await editor.getByRole('button', { name: /^中转凭证/ }).click()
  await editor.getByRole('button', { name: '添加中转凭证' }).click()
  const secondRelay = editor.getByRole('region', { name: '中转凭证 2', exact: true })
  await expect(secondRelay.getByLabel('自动创建中转账号和密码')).toBeChecked()
  await expect(secondRelay.getByLabel('绑定目标账号')).toHaveValue(await root.getAttribute('data-login-id'))
  await secondRelay.getByLabel('中转凭证 2 是否有效').uncheck()
  await editor.getByRole('button', { name: '读取指纹' }).click()
  await expect(editor.getByLabel('目标主机指纹')).toHaveValue(target.host_fingerprint)
  const saved = page.waitForResponse(response => response.request().method() === 'POST' && response.url().endsWith('/api/targets'))
  await editor.getByRole('button', { name: '保存连接' }).click()
  const response = await saved
  expect(response.status()).toBe(200)
  const result = await response.json()
  expect(result.id).toMatch(/^ssh-/)
  expect(result.credentials).toHaveLength(2)
  const connection = page.getByRole('dialog').filter({ has: page.getByRole('heading', { name: '中转连接参数' }) })
  await expect(connection).toBeVisible()
  await expect(connection.getByLabel('中转密码', { exact: true })).toHaveValue(result.credentials[0].password)
  const disabledRoot = connection.getByLabel('选择连接账号').locator(`option[value="${result.credentials[1].id}"]`)
  await expect(disabledRoot).toHaveAttribute('disabled', '')
  await expect(disabledRoot).toContainText('root')
  await connection.getByRole('button', { name: '关闭', exact: true }).click()
  const row = page.getByRole('row').filter({ hasText: '多账号设计验收' })
  await row.getByRole('button', { name: '编辑', exact: true }).click()
  await expect(editor.getByRole('button', { name: /^访问范围/ })).toHaveAttribute('aria-expanded', 'true')
  await expect(editor.getByLabel('允许的来源 IP / 网段')).toHaveValue(privateSources.join('\n'))
  await editor.getByRole('button', { name: '选择已有标签' }).click()
  await expect(editor.getByRole('button', { name: '✓ 测试环境', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(editor.getByRole('button', { name: /^高级信息/ })).toHaveCount(0)
  await expect(editor.getByLabel('目标 ID', { exact: true })).toHaveCount(0)
  await editor.getByRole('switch', { name: '机器是否有效' }).uncheck()
  await editor.getByRole('button', { name: '保存连接' }).click()
  await expect(editor).not.toBeVisible()
  await expect(row).toContainText('已禁用')
  const { items: all } = await (await page.request.get('/api/targets?page_size=100')).json()
  const stored = all.find((item: { id: string }) => item.id === result.id)
  expect(stored.logins.map((item: { user: string }) => item.user)).toEqual(['ubuntu', 'root'])
  expect(stored.relays.map((item: { enabled: boolean }) => item.enabled)).toEqual([true, false])
  expect(stored.user).toBe('root')
  // 小屏编辑也只滚动内容区，底部操作保留在窗口内。
  await page.setViewportSize({ width: 390, height: 844 })
  await row.getByRole('button', { name: '编辑', exact: true }).click()
  await expect(editor.getByRole('button', { name: '保存连接', exact: true })).toBeInViewport()
  expect(await editor.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/ssh-editor-mobile.png' })
  await editor.getByRole('button', { name: '取消', exact: true }).click()
  await page.request.delete(`/api/targets/${result.id}`, { data: {} })
})
