import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'

test('终端按中转或服务器参数连接，顶部显示模式，中转失败不回退', async ({ page }) => {
  const fixture = JSON.parse(readFileSync('.test-fixture/connection.json', 'utf8'))
  await page.goto('/')
  await page.getByLabel('管理员密码').fill(fixture.admin_password)
  await page.getByRole('button', { name: '进入中转台' }).click()
  await expect(page.getByRole('heading', { name: 'SSH 连接', exact: true })).toBeVisible()
  const url = '/?window=1&machine=' + encodeURIComponent(fixture.target.id) + '&connection='
  await page.goto(url + 'default')
  await expect(page.locator('.machine-current-address')).toHaveCount(0)
  await page.getByRole('button', { name: '查看 SSH 连接信息' }).click()
  const info = page.getByRole('dialog', { name: 'SSH 连接信息' })
  await expect(info).toContainText('中转账号')
  await expect(info).toContainText(fixture.target.relay_user)
  await expect(info).not.toContainText('允许来源')
  await expect(info).not.toContainText('主机指纹')
  await expect(info).not.toContainText('已保存，不回显')
  await info.getByRole('button', { name: '关闭连接信息' }).click()
  await expect(page.locator('.terminal-tab.active i.online')).toBeVisible()
  const capacity = page.getByRole('region', { name: '机器硬件信息' }).locator('dt').filter({ hasText: '硬盘容量（/）' })
  await expect(capacity.locator('xpath=following-sibling::dd[1]')).toHaveText('100.0 GiB')
  await expect(page.locator('.machine-header').getByRole('button', { name: '端口映射' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '重连', exact: true })).toHaveCount(0)
  const mapping = page.locator('.terminal-tabs-actions').getByRole('button', { name: '端口映射' })
  await expect(mapping).toHaveText('映射')
  await mapping.click()
  await expect(page.getByRole('dialog', { name: '端口映射配置' })).toBeVisible()
  await page.getByRole('button', { name: '关闭端口映射', exact: true }).click()
  const original = await (await page.request.get('/api/relay-endpoint')).json()
  try {
    const result = await page.request.put('/api/relay-endpoint', { data: { host: '127.0.0.1', port: 1 } })
    expect(result.ok()).toBeTruthy()
    await page.goto(url + 'default')
    await expect(page.locator('dialog[open]').filter({ hasText: '连接失败' })).toBeVisible()
    await expect(page.locator('.terminal-tab.active i.online')).toHaveCount(0)
    await expect(page.getByRole('region', { name: '机器硬件信息' })).not.toContainText('Fixture CPU')
    await expect(page.getByRole('tree', { name: '远程文件树' })).toHaveCount(0)
    await page.goto(url + 'server:default')
    await page.getByRole('button', { name: '查看 SSH 连接信息' }).click()
    await expect(info).toContainText('原始服务器账号')
    await info.getByRole('button', { name: '关闭连接信息' }).click()
    await expect(page.locator('.terminal-tab.active i.online')).toBeVisible()
    await page.screenshot({ path: 'test-results/terminal-route.png' })
  } finally {
    await page.request.put('/api/relay-endpoint', { data: original })
  }
})
