// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../encoding/json/models.js";

export interface DesktopInfo {
    "message_key"?: string;
    "message_params"?: any[] | null;
    "ready": boolean;
    "needs_setup": boolean;
    "data_dir": string;
    "listen": string;
    "error": string;
    "active": number;
    "settings": DesktopSettings;
    "version": string;
}

export interface DesktopReply {
    "status": number;
    "data": json$0.RawMessage;
}

export interface DesktopSettings {
    "external": boolean;
    "port": number;
    "connect_host": string;
}
