// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Info {
    "configured": boolean;
    "current_version": string;
    "version": string;
    "available": boolean;
    "url": string;
    "notes": string;
}
